Add bookings
alxdrvnk/java-shareit pull request #2
Opened 2023-03-16 14:42 UTC by alxdrvnk

Add bookings

2023-03-18 11:23 UTC, alxdrvnk commented
Антон привет!
Наконец-то я добрался до ревью. Долго сидел на моменте получения следующего и предыдущего бронирования. Пытался и через MapStruct парсить и через Criteria.Api - ничего не получилось. Криво-косо как-то получилось решить. Я честно пытался придумать как это оптимизировать, но все было без успешно. Еще есть несколько минорных вопросов:
1. Почему когда добавляем пользователя с похожим email, мы пользователя не добавляем, но генератор id увеличиваем? Как я понял, это же связано с тем, что транзакция коммитица и не откатывается если это специально не отлавливать, но в постмане мы просто след. пользователя добавляем с 3 id.
2. Есть ли какая-нибудь адекватная замена postmana? )

2023-03-19 17:12 UTC, Donald522 commented
> Антон привет! Наконец-то я добрался до ревью. Долго сидел на моменте получения следующего и предыдущего бронирования. Пытался и через MapStruct парсить и через Criteria.Api - ничего не получилось. Криво-косо как-то получилось решить. Я честно пытался придумать как это оптимизировать, но все было без успешно. Еще есть несколько минорных вопросов:
> 
> 1. Почему когда добавляем пользователя с похожим email, мы пользователя не добавляем, но генератор id увеличиваем? Как я понял, это же связано с тем, что транзакция коммитица и не откатывается если это специально не отлавливать, но в постмане мы просто след. пользователя добавляем с 3 id.
> 2. Есть ли какая-нибудь адекватная замена postmana? )

Привет!
Насчет MapStruct - я не фанат. Помоему написать пару конвертеров вручную - намного проще, быстрее и понятнее, чем добавлять и разбираться в новой либе, которая несет в себе кучу подводных камней и не особо упрощает жизнь. Но есть и фанаты.

1. Не понял вопрос, если честно. Что значит с "похожим email"?
2. Я такое делаю в idea. Мне удобнее. Делаешь http файл и там можно писать запросы. Не уверен правда, что это работает в community версии. Многие коллеги мои используют postman. Других инструментов не знаю.

2023-03-19 18:28 UTC, Donald522 requested changes
Привет!

Работа хорошая, как всегда. Некоторые места вызывают вопросы, особенно в части обработки ошибок. 
На вопросы ответил.

2023-03-19 18:28 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (booking.getBooker().getId() != userId && booking.getItem().getOwner().getId() != userId) {
Это условие можно добавить в запрос в бд:
`select * from booking where id = :id AND (booker = :userId OR owner = :userId)`

2023-03-19 18:28 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        userService.getUserBy(userId);
Лишнее

2023-03-19 18:28 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                return bookingRepository.findAllByBookerIdAndEndBeforeOrderByStartDesc(userId, LocalDateTime.now());
В now() лучше передавать параметр clock.
Так будет проще в тестах, можно будет зафиксировать now и тесты будут стабильнее

А еще кажется метод может работать по-разному в разных таймзонах. Это значит, что если есть например 2 ДЦ в разных таймзонах, то они будут(могут) давать разные результаты

2023-03-19 18:28 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        switch (state) {
Этот switch явно просится вынести его в отдельный класс, потому что дублируется между 2 методами.
Я обычно такие вещи делаю так. Создаю интерфейс
```
BookingProvider {
  public Collection< Booking > getAllBookingsOfUser(Long userId, String state);
  public Collection< Booking > getAllBookingsForOwnerItems(Long userId, String state)
}
```

Этому репозиторию столько реализаций, сколько ветвей в switch + реализация - dispatcher, где собственно находится условие выбора. Это может switch либо же доставать нужную реализацию по ключу

```
public class BookingProviderSelector implements BookingProvider {
   private final Map<BookingState, BookingProvider> providers;

  public Collection< Booking > getAllBookingsForOwnerItems(Long userId, String state) {
    // ....
    BookinkProvider provider = providers.get(state);
    provider.getAllBookingsForOwnerItems();
    //....
  }
}
```

2023-03-19 18:28 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/booking/service/State.java
> +                     "Test get user bookings by 'UNSUPPORTED_STATUS' state");
Можно добавить в текст ошибки значение переданного параметра.

2023-03-19 18:28 UTC, Donald522 commented on src/main/resources/schema.sql
> +                                     booker_id INTEGER,
По booker_id стоит индекс добавить, по нему много запросов идет.
По item_id возможно тоже.

2023-03-19 18:28 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +@Transactional(readOnly = true)
Над классом не обязательно ставить, достаточно над методом только

2023-03-19 18:28 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    @Transactional
А сколько здесь обновляется таблиц? Не уверен, что тут транзакция нужна

2023-03-19 18:28 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +//        User userDb;
Я так понимаю вопрос твой касался этой части кода
А зачем тут rollback? Тут же только одна таблица меняется. Если не смогли вставить в users, то и откатывать нечего получается

Если вопрос в том, почему не откатывается сгенеренный id, то это нормально. Для генерации тут используется sequence, они не транзакционные, зато очень производительные. Представь, что у тебя 2 транзакции параллельные идут, для одной сгенерился id = 1, для другой id = 2. Вторая успешно завершается, а первая нет. Если в такой случае вернуть значение id = 1, то потом у нас случится конфликт при попытке вставить с id = 2 второй раз. Запоминать неудачные id не вариант - это очень плохо скажется на производительности, тк это хранилище станет точкой блокировки для всех параллельных транзакций.

2023-03-22 08:18 UTC, alxdrvnk commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +            throw new ShareItBadRequest(String.format("Item with Id: %d doesn't available", item.getId()));
Тогда, я не понимаю что нужно. В "постмане" просят вернуть 400 код.

2023-03-22 08:41 UTC, alxdrvnk commented
Антон, привет!

Большое спасибо за красивую замену switch, надеюсь я правильно понял концепт. 
MapStruct постараюсь переписать в след. или через 1 спринт - намучался я с ним, а толку что-то не много, так еще и дружи её с lombok. Хотелось посмотреть, что за зверь такой.

2023-03-22 15:04 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +            throw new ShareItBadRequest(String.format("Item with Id: %d doesn't available", item.getId()));
Тогда ок. Я не знаком с тестами постмана

2023-03-22 15:05 UTC, Donald522 commented
> Антон, привет!
> 
> Большое спасибо за красивую замену switch, надеюсь я правильно понял концепт. MapStruct постараюсь переписать в след. или через 1 спринт - намучался я с ним, а толку что-то не много, так еще и дружи её с lombok. Хотелось посмотреть, что за зверь такой.

С ломбок его подружить можно кажется порядком зависимостей в pom.xml. Тоже сталкивался с этим когда-то. С тех пор не люблю)

2023-03-22 15:09 UTC, Donald522 approved these changes
Привет!

Все хорошо сейчас.

2023-03-22 15:09 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/booking/service/provider/BookingProviderSelector.java
> +        providers = new EnumMap<>(BookingState.class);
Можно так, а можно создавать эту мапу в конфиге бином и чтобы спринг ее инжектил.
Это даст возможность в тестах подменять ее, ну и получится более чистое разделение конфига и кода: при добавлении новой реализации будет меняться только конфиг

2023-03-22 16:01 UTC, merged