Add item requests
alxdrvnk/java-shareit pull request #3
Opened 2023-03-24 15:26 UTC by alxdrvnk

Add item requests

2023-03-26 09:35 UTC, alxdrvnk commented
Антон, привет!
У меня есть несколько вопросов:
1.	Меня немного смущает то как я решил задачи получения предметов со следующим и предыдущим бронированием и получение запросов на предметы. Мне кажется, что они выглядят как костыль + еще используется Transformer, как я понимаю такой подход уже устарел. Есть ли какое-то более красивое решение такой задачи?
2.	Немного смущает, что я вытаскиваю из репозитория сразу DTO объект. Как я понял, DTO – это прослойка между API и Controller. Правильно ли доставать из репозитория DTO объект?
3.	Стоит ли делать отельный сервис для валидации объекта? Т.е. создать сервис, в котором не будет CRUD-а, а будет только проверки по типу «существует ли пользователь», «есть ли у пользователя X поле» и так далее. Вообще такое практикуется на реальных проектах?

2023-03-26 18:45 UTC, Donald522 commented
> Антон, привет! У меня есть несколько вопросов:
> 
> 1. Меня немного смущает то как я решил задачи получения предметов со следующим и предыдущим бронированием и получение запросов на предметы. Мне кажется, что они выглядят как костыль + еще используется Transformer, как я понимаю такой подход уже устарел. Есть ли какое-то более красивое решение такой задачи?
> 2. Немного смущает, что я вытаскиваю из репозитория сразу DTO объект. Как я понял, DTO – это прослойка между API и Controller. Правильно ли доставать из репозитория DTO объект?
> 3. Стоит ли делать отельный сервис для валидации объекта? Т.е. создать сервис, в котором не будет CRUD-а, а будет только проверки по типу «существует ли пользователь», «есть ли у пользователя X поле» и так далее. Вообще такое практикуется на реальных проектах?

1. Насколько вижу, то можно добавить в ItemRequest класс поле List<Item> и как минимум получение запросов станет проще. Насчет первого и последнего бронирования - думаю тут можно было сделать и отдельными запросами в базу. Про Transformer не подскажу, я с ним не работал ни разу.

2. Отписал в коде уже, что это не очень хорошо, да. dto - это транспортное представление, например между фронтом и бэкэндом. Часто хранить данные удобнее в ином виде, чем показывать в клиентском приложении. К тому же это помогает разделить технологии - dto классы часто обвешаны jackson аннотации, а модельные (их еще называют value objects или entity objects) например хибернейтовскими.

3. Сервис имеешь ввиду класс? Да, имеет смысл. 
В жизни тут может быть все сильно по разному. Простые проверки (типа null/not-null, или формат) часто не пишут вручную, а это приходит из коробки от фреймфорка, такие проверки автоматически превращаются в 400ки для клиента. Если проверка более сложная, то пишут, да.

2023-03-26 18:45 UTC, Donald522 requested changes
Привет!

На вопросы постарался ответить, пару комментов тоже оставил.

2023-03-26 18:45 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/request/repository/impl/transformer/ItemRequestDtoTransformer.java
> +    public Object transformTuple(Object[] objects, String[] strings) {
Почему Object в return type?

2023-03-26 18:45 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/item/repository/impl/ItemWithBookingsRepositoryImpl.java
> +                                    "DENSE_RANK () OVER (ORDER BY last_booking.END_DATE DESC, " +
Не проще сделать было пагинацию через limit... offset ?
А еще смущает, что dense_rank будет давать не стабильный размер страницы

2023-03-26 18:45 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/request/model/ItemRequest.java
>      LocalDateTime created;
Если тут добавить поле List<Item>, то сильно проще станет, кажется

2023-03-26 18:45 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/item/mapper/ItemMapper.java
> +                .requestId(requestId)
lastBooking, nextBooking тут не пропущено?

2023-03-26 18:45 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/item/mapper/ItemMapper.java
> +        // Если делать через stream, то нужно делать toItemDto метод static - это смотрится как то странно
Можно же через this обращаться
`.map(this::toItemDto)`
Когда ты из одного метода вызываешь другой приватный метод того же класса, ты же не делаешь его статическим. Там есть неявное обращение через this, здесь надо явно писать.

2023-03-28 13:21 UTC, alxdrvnk commented
Антон, привет!

Попытался решить  задачу поиска следующего и предыдущего бронирования через несколько запросов.

2023-03-28 19:02 UTC, Donald522 approved these changes
Привет!

Кажется, сейчас получилось проще. Давай так оставим.

2023-03-28 19:05 UTC, merged