Add docker
alxdrvnk/java-shareit pull request #4
Opened 2023-03-31 12:42 UTC by alxdrvnk

add docker

2023-03-31 17:13 UTC, alxdrvnk commented
Антон привет!

Есть такой вопрос: стоит ли пользоваться группировкой валидаторов (Grouping Validation Constraints)?

2023-04-01 15:26 UTC, Donald522 requested changes
Привет!

Все в общем хорошо, оставил пару комментариев небольших.

Насчет constraint group validation - я не пользовался, но на первый взгляд ничего плохого в этом не вижу.

2023-04-01 15:26 UTC, Donald522 commented on server/src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +            "ORDER BY b.item_id ASC, b.END_DATE DESC", nativeQuery = true)
Подумал, что тут можно не тащить весь список предыдущих бронирований и в коде брать самое последнее из них, а решить эту задачу с помощью оконных функций бд

```
with prev_booking as
(
  select 
     *,
     row_number() over (partition by item_id order by end_date desc) as prev_booking_num
  from bookings
  where 1=1
  and ...
)

select .... 
  from prev_booking 
where   prev_booking_num = 1;
```

Не уверен, что сходу написал правильно, но идея примерно такая)

Но это так, можешь и не делать, просто знай, что так можно

2023-04-01 15:26 UTC, Donald522 commented on server/src/main/resources/schema.sql
> +                                     created_date TIMESTAMP,
тут по-хорошему тоже not null надо
И можно default значение добавить

А еще timestamp стоит использовать с таймзоной
timestamp with time zone

2023-04-01 15:26 UTC, Donald522 commented on docker-compose.yaml
> +    image: postgres:12.14-alpine
А чего не 14 постгрес?

2023-04-01 15:26 UTC, Donald522 commented on docker-compose.yaml
> +      - POSTGRES_USER=root
Наверное лучше сделать своего пользователя для базы, назвать например shareit
Из-под root ходить не очень

2023-04-02 07:09 UTC, alxdrvnk commented
Антон привет!

Спасибо за подсказку про оконные функции (постараюсь успеть реализовать их до проверки).

2023-04-02 08:13 UTC, Donald522 requested changes
Привет!

Еще заметил, что зависимость на валидацию в сервере осталась, ее надо бы убрать

2023-04-02 08:13 UTC, Donald522 commented on server/pom.xml
> +            <artifactId>spring-boot-starter-validation</artifactId>
В сервере кстати не должно быть этой зависимости

2023-04-02 09:49 UTC, alxdrvnk commented
Вроде бы поправил. По всей видимости, недавно поменяли тесты для проекта, пришлось еще добавить сортировку.

2023-04-02 11:35 UTC, Donald522 approved these changes

2023-04-02 11:37 UTC, merged